// ROUND_LOGS_ARCHIVE - 日志文件夹打包下载
// 玩家/管理员可见字符串走 LANG()，key 由 `nova-i18n key client "<模板>"` 校验后写入
// strings/i18n/{en,zh-Hans}/client.json；请勿手改 key。
//
// The stock "Download Folder" option ftp()s every file in the folder
// separately, which makes the client raise one save prompt per file - a dozen
// confirmations for a single round's logs. This module adds a second option
// that packs the whole folder (recursively) into one archive and sends it with
// a single ftp(), plus a one-click verb for the current round.
//
// The only core touchpoint is the option list and switch branch in
// /client/proc/browse_files, marked with TIANGUAN EDIT in code/__HELPERS/files.dm.

/// Where generated archives are written. Deliberately OUTSIDE data/logs so an
/// archive never shows up in the log browser, never gets swallowed by a later
/// archive of a parent folder, and is never picked up by log collection.
#define LOG_ARCHIVE_DIR "data/log_archives/"
/// How long an archive is kept before it is deleted, so a slow ftp() transfer
/// is never cut short.
#define LOG_ARCHIVE_LIFETIME (30 MINUTES)
/// The log root itself: archiving it would tar up every round ever recorded
/// while the server sits frozen, so it is refused outright.
#define LOG_ARCHIVE_FORBIDDEN_ROOT "data/logs/"

/// Set once the archive directory has been prepared and swept this round.
GLOBAL_VAR_INIT(log_archive_dir_ready, FALSE)

/**
 * Creates the archive staging directory and clears anything left in it.
 *
 * The delete timer does not survive a reboot, so archives from previous rounds
 * would otherwise pile up forever. Sweeping on first use each round keeps the
 * directory bounded without needing to stat file ages, which DM cannot do.
 */
/proc/prepare_log_archive_dir()
	if(GLOB.log_archive_dir_ready)
		return
	GLOB.log_archive_dir_ready = TRUE
	for(var/leftover in flist(LOG_ARCHIVE_DIR))
		fdel("[LOG_ARCHIVE_DIR][leftover]")
	// Writing a file is also how the directory gets created; tar will not
	// create its own output directory.
	text2file("Staging area for admin log downloads. Cleared every round.", "[LOG_ARCHIVE_DIR]README.txt")

/// Deletes a finished download archive once it has had time to transfer.
/proc/delete_log_archive(archive_path)
	fdel(archive_path)

/**
 * Packs every file in the given folder into a single archive and sends it with
 * one ftp(). Recurses into subfolders (job/, ahelp/, profiler/ and so on).
 *
 * Uses the system tar through world.shelleo(), so DreamDaemon must be running
 * in Trusted mode (the default for TGS deployments, see .tgs.yml).
 * - UNIX: GNU tar produces a .tar.gz.
 * - MS_WINDOWS: bsdtar (shipped in System32 since Win10 1803) produces a .zip.
 *
 * Returns TRUE when the request was handled one way or another, and FALSE only
 * when the admin declined the confirmation, so browse_files() can let them keep
 * browsing instead of dropping out of the dialog.
 */
/client/proc/download_folder_as_archive(path)
	// This proc hands a path to a shell, so it checks rights itself rather than
	// trusting every present and future caller to have done it.
	if(!check_rights_for(src, R_ADMIN))
		return TRUE

	if(path == LOG_ARCHIVE_FORBIDDEN_ROOT)
		to_chat(src, span_boldwarning(LANG("client.7aea08c3c3903602", null)), confidential = TRUE)
		return TRUE

	if(!length(flist(path)))
		to_chat(src, span_boldwarning(LANG("client.cc8ba79bc21a9d99", list(path))), confidential = TRUE)
		return TRUE

	if(tgui_alert(src, LANG("client.9f71aac0a8a6810e", list(path)), LANG("client.15bc27b6fe454546", null), list("Yes", "No")) != "Yes")
		return FALSE

	// The folder can be rotated away or emptied while the confirmation is open.
	if(!length(flist(path)))
		to_chat(src, span_boldwarning(LANG("client.cc8ba79bc21a9d99", list(path))), confidential = TRUE)
		return TRUE

	if(file_spam_check())
		return TRUE

	// Log paths are generated by the server, but the log root can be overridden
	// from the DreamDaemon command line, and double quotes do NOT stop a POSIX
	// shell from expanding $(), backticks or $VAR. Whitelist instead of trust.
	var/static/regex/shell_safe_path = regex(@"^[A-Za-z0-9_./ -]+$")
	if(!shell_safe_path.Find(path))
		to_chat(src, span_boldwarning(LANG("client.2a9ef63f1a5c0307", list(path))), confidential = TRUE)
		return TRUE

	prepare_log_archive_dir()

	// The flattened source path keeps archives of different folders apart, the
	// timestamp keeps repeat downloads of the same folder apart.
	var/archive_name = "[pathflatten(copytext_char(path, 1, -1))]_[time2text(world.realtime, "YYYYMMDD-hhmmss", TIMEZONE_UTC)]"
	var/archive_path
	var/command
	if(world.system_type == UNIX)
		archive_path = "[LOG_ARCHIVE_DIR][archive_name].tar.gz"
		command = "tar -czf \"[archive_path]\" -C \"[path]\" ."
	else
		// Unqualified so cmd resolves it from System32 on PATH: an absolute
		// quoted path as the first token confuses cmd /c's quote handling.
		archive_path = "[LOG_ARCHIVE_DIR][archive_name].zip"
		command = "tar -a -c -f \"[archive_path]\" -C \"[path]\" ."

	var/list/shell_result = world.shelleo(command)
	var/errorlevel = shell_result[1]
	var/stderr = shell_result[3]

	if(!fexists(archive_path))
		fdel(archive_path)
		to_chat(src, span_boldwarning(LANG("client.9b753d182153e9a3", list(archive_path, errorlevel))), confidential = TRUE)
		if(stderr)
			to_chat(src, span_boldwarning("tar: [stderr]"), confidential = TRUE)
		return TRUE

	// tar exits 1 when a file grew while it was being read, which is normal for
	// the round that is still being played. The archive is still valid.
	if(errorlevel)
		to_chat(src, span_warning(LANG("client.17c151c01f589ad7", list(errorlevel))), confidential = TRUE)

	message_admins("[key_name_admin(src)] downloaded the contents of [path] as a single archive ([archive_path]).")
	log_admin("[key_name(src)] downloaded the contents of [path] as a single archive ([archive_path]).")
	src << ftp(file(archive_path))
	to_chat(src, span_notice(LANG("client.04c7cd22dc6cb17f", list(archive_path))), confidential = TRUE)
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(delete_log_archive), archive_path), LOG_ARCHIVE_LIFETIME)
	return TRUE

/// One-click verb: download the whole current round's log folder as one archive.
ADMIN_VERB(download_current_round_logs, R_ADMIN, "下载当前回合日志", "Download all logfiles for the current round as a single compressed archive.", ADMIN_CATEGORY_MAIN)
	user.download_folder_as_archive("[GLOB.log_directory]/")

#undef LOG_ARCHIVE_DIR
#undef LOG_ARCHIVE_LIFETIME
#undef LOG_ARCHIVE_FORBIDDEN_ROOT
