// ROUND_LOGS_ARCHIVE - 日志文件夹 ZIP 打包下载
// 本模块按维护者要求置于 modular_nova/modules/（见 PR 评论）；core 钩子按天关规范
// 使用 TIANGUAN EDIT 标记，全部逻辑在此。

/// Downloads every file in the given folder as a single compressed archive.
/// The previous behaviour of ftp()-ing each file individually opened one save
/// prompt per file in the client, which is painful for a whole round's logs.
///
/// Uses the system tar through shell(), so DreamDaemon must be running in
/// Trusted mode (the default for TGS deployments, see .tgs.yml).
/// - MS_WINDOWS: bsdtar (C:\Windows\System32\tar.exe) creates a real .zip via -a.
/// - UNIX: GNU tar creates a .tar.gz archive.
///
/// The archive is sent with a single ftp() and deleted after a delay so a slow
/// transfer is never cut short.
/client/proc/download_folder_as_archive(path)
	// Paths are quoted so the shell never sees unescaped characters, even
	// though log folder and file names are generated by the server itself.
	// The timestamp keeps concurrent downloads of the same folder apart.
	var/timestamp = time2text(world.realtime, "YYYYMMDD-hhmmss")
	var/archive_path
	var/command
	if(world.system_type == UNIX)
		archive_path = "[copytext_char(path, 1, -1)]_[timestamp].tar.gz"
		command = "tar -czf \"[archive_path]\" -C \"[path]\" ."
	else
		archive_path = "[copytext_char(path, 1, -1)]_[timestamp].zip"
		command = "\"C:/Windows/System32/tar.exe\" -a -c -f \"[archive_path]\" -C \"[path]\" ."

	shell(command)
	if(!fexists(archive_path))
		to_chat(src, span_boldwarning("Error: download_folder_as_archive(): Failed to create [archive_path]. The server must be running in Trusted mode and have tar available."))
		return
	message_admins("[key_name_admin(src)] downloaded the contents of [path] as a single archive ([archive_path]).")
	src << ftp(file(archive_path))
	to_chat(src, "Attempting to send [archive_path], this may take a fair few minutes if the folder is very large.", confidential = TRUE)
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(cleanup_download_archive), archive_path), 30 MINUTES)

/// Deletes a temporary download archive after it has had time to transfer.
/proc/cleanup_download_archive(path)
	fdel(path)

/// One-click verb: download the entire current round's log folder as a single archive.
ADMIN_VERB(download_current_round_logs, R_ADMIN, "Download Current Round Logs", "Download all logfiles for the current round as a single compressed archive.", ADMIN_CATEGORY_MAIN)
	var/confirmation = tgui_alert(user, "Download ALL logs for the current round as a single compressed archive? Very large log folders may briefly lag the server while the archive is created.", "Download Current Round Logs", list("Yes", "No"))
	if(confirmation != "Yes")
		return
	if(user.file_spam_check())
		return
	user.download_folder_as_archive("[GLOB.log_directory]/")
